export const cv = {
  basics: {
    name: 'Jakub Kulewicz',
    headline: 'Software Developer & Scrum Master',
    roleLine: 'SOFTWARE DEVELOPER',
    email: 'jakubkulewicz05@gmail.com',
    phone: '+48 664-987-865',
    location: 'Wrocław, Polska',
    github: { url: 'https://github.com/S0ul3r', label: 'GitHub' },
    linkedin: { url: 'https://www.linkedin.com/in/jakub-k-977216129/', label: 'LinkedIn' },
  },
  summary: {
    content: 'Full-stack developer with 4+ years of commercial experience in building and maintaining scalable microservices using C#/.NET Core, TypeScript, and React. Scrum Master leading a team of 5 developers in Agile/Scrum environments. Strong background in CI/CD, cloud solutions (Azure), and multi-database architectures. Owner of PolishTango.com, a platform focused on Argentine tango events across Poland. Passionate about clean code, automation, and delivering business value.',
  },
  nav: [
    { label: 'Home', href: '#home' },
    { label: 'About', href: '#about' },
    { label: 'Work', href: '#work' },
    { label: 'Projects', href: '#projects' },
    { label: 'Contact', href: '#contact' },
  ],
  services: [
    {
      title: 'APIs & microservices',
      body: 'C# / .NET Core services for time-tracking and ERP clients, designed for performance and clear contracts.',
      icon: 'plugs',
    },
    {
      title: 'Web applications',
      body: 'React and TypeScript products with real users, including PolishTango and TangoDJ.',
      icon: 'browser',
    },
    {
      title: 'Azure & cloud',
      body: 'Cloud-hosted systems plus Microsoft Azure Fundamentals certification from 2023.',
      icon: 'cloud',
    },
    {
      title: 'CI/CD',
      body: 'Azure DevOps pipelines that cut manual release work and deployment time.',
      icon: 'flow-arrow',
    },
    {
      title: 'Data stores',
      body: 'PostgreSQL, MySQL, and NoSQL layouts tuned for the access patterns they serve.',
      icon: 'database',
    },
    {
      title: 'Scrum delivery',
      body: 'Scrum Master for a team of five, with ceremonies that keep delivery predictable.',
      icon: 'users-three',
    },
  ],
  skillColumns: [
    {
      name: 'FRONT-END',
      keywords: ['TypeScript', 'JavaScript', 'React', 'Next.js', 'Tailwind', 'HTML', 'CSS'],
    },
    {
      name: 'BACK-END',
      keywords: ['C#', '.NET Core', 'SQL', 'Python', 'MySQL', 'PostgreSQL', 'NoSQL'],
    },
    {
      name: 'CLOUD & TOOLS',
      keywords: ['Azure', 'Azure DevOps', 'CI/CD', 'Git', 'GitHub', 'Lua', 'Unity'],
    },
  ],
  experience: [
    {
      company: 'Unit4',
      position: 'Software Engineer (Junior → Mid)',
      location: 'Poland',
      period: '2021 - current',
      website: 'https://www.unit4.com/',
      description: 'Led a team of 5 developers as Scrum Master, facilitating Agile ceremonies and improving delivery predictability. Designed and developed scalable time-tracking microservices using C#/.NET Core and TypeScript, serving enterprise ERP clients. Architected multi-database solutions (PostgreSQL, MySQL, NoSQL) optimised for performance and scalability. Implemented CI/CD pipelines in Azure DevOps, reducing deployment time and manual errors.',
      tags: ['C#', '.NET Core', 'TypeScript', 'React', 'Azure', 'Azure DevOps', 'PostgreSQL', 'MySQL', 'NoSQL'],
    },
    {
      company: 'Personal side projects',
      position: 'Software Developer',
      location: '',
      period: '2019 - Present',
      website: 'https://aurora-wow.wtf/marketplace/',
      description: 'Developed and sold automation scripts for World of Warcraft using Lua, focusing on performance and maintainability.',
      tags: ['Lua', 'Python', 'Git'],
    },
    {
      company: 'ZoneIT',
      position: 'Junior Software Engineer',
      location: 'Poland',
      period: '2019',
      website: 'https://zoneit.pl/',
      description: 'Developed a website and handled its database for a hospital in Zurich using Laravel 5 with PHP, JS, HTML/CSS, MySQL.',
      tags: ['PHP', 'Laravel', 'JavaScript', 'MySQL', 'HTML', 'CSS'],
    },
    {
      company: 'Takeaway.com',
      position: 'Customer Service',
      location: 'Poland',
      period: '2016',
      website: 'https://www.takeaway.com/be-pl',
      description: 'Monitored and managed customer orders, implemented restaurant page updates and resolved technical issues for restaurant partners using the internal framework.',
      tags: [],
    },
  ],
  education: [
    { school: 'Wrocław University of Technology', area: 'Biomedical Engineering & Teleinformatics', period: '2014 - 2021', website: 'https://pwr.edu.pl/' },
    { school: 'High School No. XIV Wrocław', area: 'Bilingual biol-chem', period: '2011 - 2014', website: 'https://lo14.wroc.pl/' },
    { school: "Grazyna's Bacewicz Music School", area: 'Piano', period: '2002 - 2008', website: 'https://www.gov.pl/web/smwroclaw' },
  ],
  projects: [
    {
      name: 'PolishTango',
      website: 'https://polishtango.com/',
      description:
        'Owner of PolishTango.com, a public milonga calendar for tango events across Poland, with month/week/list views, voivodeship filters, and a trusted-editor admin for reviewing and publishing events.',
      tags: ['Next.js', 'React', 'TypeScript', 'Neon', 'Tailwind'],
      image: '/media/PolishTango.png',
    },
    {
      name: 'World of Warcraft rotations',
      website: 'https://github.com/S0ul3r/Aurora-Bober-Rogue',
      description: 'Aurora Bober Rogue rotation by S0ul3r for World of Warcraft.',
      tags: ['Lua'],
      image: 'https://img.youtube.com/vi/kZ0IGSSiYlM/maxresdefault.jpg',
      videoUrl: 'https://www.youtube.com/watch?v=kZ0IGSSiYlM',
      previewVideo: '/media/wow-preview.mp4',
    },
    {
      name: 'TangoDJ',
      website: 'https://tango-dj.vercel.app/library',
      description:
        'Milonga desk for Argentine tango DJs: organize tango / vals / milonga / cortina libraries into tandas and night queues, with Spotify Connect or local file playback and Supabase sync.',
      tags: ['Next.js', 'React', 'TypeScript', 'Supabase', 'Tailwind'],
      image: '/media/TangoDJ.png',
    },
    {
      name: 'CoinFlipWeb',
      website: 'https://coinflip-collect.vercel.app/',
      description:
        'Collection-first PWA for Polish commemorative coins: catalog browse, personal collection, wishlist, series tracking, and photo-based coin identification (PL/EN).',
      tags: ['React', 'TypeScript', 'Vite', 'Supabase', 'PWA'],
      image: '/media/CoinFlipWeb.png',
    },
    {
      name: 'Macro execute and recorder',
      website: 'https://github.com/S0ul3r/Bober-macro-maker',
      description: 'Macro automation tool, mainly for the game "Where Winds Meet". Create custom macros to cast combos that can be used in game.',
      tags: ['Python'],
      image: '/media/Bober-macro-maker.png',
    },
    {
      name: 'boberwrapped',
      website: 'https://github.com/S0ul3r/boberwrapped',
      description:
        'Spotify “wrapped” style app: top artists/tracks/genres, mood radar, recently played, and playlist browser using Spotify Web API + OAuth PKCE.',
      tags: ['TypeScript'],
      image: '/media/boberwrapped.png',
    },
    {
      name: 'BoberInSpire',
      website: 'https://github.com/S0ul3r/BoberInSpire',
      description:
        'Hybrid C# + Python assistant for Slay the Spire 2: a C# mod exports combat and reward state to JSON; a Python overlay shows real-time damage/block summaries, relic info, and card-pick advice (Mobalytics tiers + deck heuristics) in a semi-transparent always-on-top window.',
      tags: ['C#', 'Python'],
      image: '/media/BoberInSpire.png',
    },
    {
      name: 'Min spendings',
      website: 'https://github.com/S0ul3r/min_spendings',
      description: 'Mobile application for android and iOS to track your monthly spendings, so you have better overview how much and on what you are spending your money.',
      tags: ['React Native', 'TypeScript'],
      image: '/media/min_spendings.png',
      imageFit: 'contain',
    },
    {
      name: 'Rogue Survivor',
      website: 'https://github.com/S0ul3r/Rogue-Survivor',
      description: '2D Unity based rogue-like game.',
      tags: ['C#', 'Unity'],
      image: '/media/Rogue_Survivor.png',
    },
  ],
  skills: [
    { name: 'Programming Languages', keywords: ['TypeScript', 'JavaScript', 'C#', 'SQL', 'Lua', 'Python'] },
    { name: 'Frameworks', keywords: ['.NET Core', 'React', 'Laravel'] },
    { name: 'Cloud & DevOps', keywords: ['Azure', 'Azure DevOps', 'CI/CD'] },
    { name: 'Databases', keywords: ['MySQL', 'PostgreSQL', 'NoSQL'] },
    { name: 'Tools & Practices', keywords: ['GitHub', 'Git', 'Agile', 'Scrum (Scrum Master)'] },
  ],
  languages: [
    { language: 'Polish', fluency: 'Native' },
    { language: 'English', fluency: 'C2 (Proficient)' },
  ],
  certifications: [
    { title: 'Microsoft Certified: Azure Fundamentals', issuer: 'Microsoft', date: '2023' },
    { title: 'CCNA: Networking, Security, and Automation', issuer: 'Cisco', date: '2022' },
    { title: 'CCNA: Switching, Routing, and Wireless Essentials', issuer: 'Cisco', date: '2022' },
    { title: 'Python Data Science Toolbox & Unit Testing', issuer: 'Datacamp', date: '2021' },
    { title: 'Skiing Instructor', issuer: 'SITN', date: '2020' },
  ],
  interests: [
    { name: 'Music', keywords: ['Playing piano', 'Indie', 'Electronic', 'Rock'] },
    { name: 'Sports', keywords: ['Skiing', 'Badminton', 'Hockey'] },
    { name: 'Dancing', keywords: ['Ballroom', 'Salsa', 'Son', 'Argentine Tango'] },
  ],
  interestsVideo: {
    url: 'https://www.youtube.com/watch?v=1xnJAcBFodk',
    thumbnail: 'https://img.youtube.com/vi/1xnJAcBFodk/maxresdefault.jpg',
    label: 'Piano playing',
  },
};

export const devicons = {
  'TypeScript': 'devicon-typescript-plain',
  'JavaScript': 'devicon-javascript-plain',
  'C#': 'devicon-csharp-plain',
  'SQL': 'devicon-azuresqldatabase-plain',
  'Lua': 'devicon-lua-plain',
  'Python': 'devicon-python-plain',
  '.NET Core': 'devicon-dotnetcore-plain',
  'React': 'devicon-react-original',
  'React Native': 'devicon-react-original',
  'Next.js': 'devicon-nextjs-plain',
  'Vite': 'devicon-vitejs-plain',
  'Supabase': 'devicon-supabase-plain',
  'Neon': 'devicon-postgresql-plain',
  'Tailwind': 'devicon-tailwindcss-plain',
  'PWA': 'devicon-chrome-plain',
  'Laravel': 'devicon-laravel-original',
  'Azure': 'devicon-azure-plain',
  'Azure DevOps': 'devicon-azure-plain',
  'CI/CD': 'devicon-githubactions-plain',
  'MySQL': 'devicon-mysql-plain',
  'PostgreSQL': 'devicon-postgresql-plain',
  'NoSQL': 'devicon-mongodb-plain',
  'GitHub': 'devicon-github-original',
  'Git': 'devicon-git-plain',
  'Unity': 'devicon-unity-plain',
  'PHP': 'devicon-php-plain',
  'HTML': 'devicon-html5-plain',
  'CSS': 'devicon-css3-plain',
};

export const tagHue = {
  TypeScript: '#3178c6',
  JavaScript: '#f7df1e',
  'C#': '#68217a',
  SQL: '#e38c00',
  Lua: '#000080',
  Python: '#3776ab',
  '.NET Core': '#512bd4',
  React: '#61dafb',
  'React Native': '#61dafb',
  'Next.js': '#e4e4e4',
  Vite: '#646cff',
  Supabase: '#3ecf8e',
  Neon: '#00e599',
  Tailwind: '#38bdf8',
  PWA: '#5a0fc8',
  Laravel: '#ff2d20',
  Azure: '#0078d4',
  'Azure DevOps': '#0078d4',
  'CI/CD': '#2088ff',
  MySQL: '#4479a1',
  PostgreSQL: '#336791',
  NoSQL: '#13aa52',
  GitHub: '#e4e4e4',
  Git: '#f05032',
  Unity: '#e4e4e4',
  PHP: '#777bb4',
  HTML: '#e44d26',
  CSS: '#1572b6',
  WebGL: '#990000',
  Backend: '#8b5cf6',
  Frontend: '#22d3ee',
};
