export const cv = {
  basics: {
    name: 'Jakub Kulewicz',
    headline: 'Software Developer & Scrum Master',
    email: 'jakubkulewicz05@gmail.com',
    phone: '+48 664-987-865',
    location: 'Wrocław, Polska',
    github: { url: 'https://github.com/S0ul3r', label: 'GitHub' },
    linkedin: { url: 'https://www.linkedin.com/in/jakub-k-977216129/', label: 'LinkedIn' },
  },
  summary: {
    content: 'Full-stack developer with 4+ years of commercial experience in building and maintaining scalable microservices using C#/.NET Core, TypeScript, and React. Scrum Master leading a team of 5 developers in Agile/Scrum environments. Strong background in CI/CD, cloud solutions (Azure), and multi-database architectures. Passionate about clean code, automation, and delivering business value.',
  },
  nav: [
    { label: 'Experience', href: '#experience' },
    { label: 'Projects', href: '#projects' },
    { label: 'Skills', href: '#skills' },
    { label: 'Certifications', href: '#certifications' },
    { label: 'Education', href: '#education' },
    { label: 'Languages', href: '#languages' },
    { label: 'Interests', href: '#interests' },
  ],
  experience: [
    {
      company: 'Unit4',
      position: 'Software Engineer (Junior → Mid)',
      location: 'Poland',
      period: '2021 - current',
      website: 'https://www.unit4.com/',
      description: 'Led a team of 5 developers as Scrum Master, facilitating Agile ceremonies and improving delivery predictability. Designed and developed scalable time-tracking microservices using C#/.NET Core and TypeScript, serving enterprise ERP clients. Architected multi-database solutions (PostgreSQL, MySQL, NoSQL) optimised for performance and scalability. Implemented CI/CD pipelines in Azure DevOps, reducing deployment time and manual errors.',
      tags: ['C#', '.NET Core', 'TypeScript', 'React', 'Azure', 'Azure DevOps', 'PostgreSQL', 'MySQL', 'NoSQL'],
    },
    {
      company: 'Personal side projects',
      position: 'Software Developer',
      location: '',
      period: '2019 - Present',
      website: 'https://aurora-wow.wtf/marketplace/',
      description: 'Developed and sold automation scripts for World of Warcraft using Lua, focusing on performance and maintainability.',
      tags: ['Lua', 'Python', 'Git'],
    },
    {
      company: 'ZoneIT',
      position: 'Junior Software Engineer',
      location: 'Poland',
      period: '2019',
      website: 'https://zoneit.pl/',
      description: "Developed a website and handled it's database for a hospital in Zurich using Laravel 5 with PHP, JS, HTML/CSS, MySQL.",
      tags: ['PHP', 'Laravel', 'JavaScript', 'MySQL', 'HTML', 'CSS'],
    },
    {
      company: 'Takeaway.com',
      position: 'Customer Service',
      location: 'Poland',
      period: '2016',
      website: 'https://www.takeaway.com/be-pl',
      description: 'Monitored and managed customer orders, implemented restaurant page updates and resolved technical issues for restaurant partners using the internal framework.',
      tags: [],
    },
  ],
  education: [
    { school: 'Wrocław University of Technology', area: 'Biomedical Engineering & Teleinformatics', period: '2014 - 2021', website: 'https://pwr.edu.pl/' },
    { school: 'High School No. XIV Wrocław', area: 'Bilingual biol-chem', period: '2011 - 2014', website: 'https://lo14.wroc.pl/' },
    { school: "Grazyna's Bacewicz Music School", area: 'Piano', period: '2002 - 2008', website: 'https://www.gov.pl/web/smwroclaw' },
  ],
  projects: [
    {
      name: 'Macro execute and recorder',
      website: 'https://github.com/S0ul3r/Bober-macro-maker',
      description: 'Macro automation tool, mainly for the game "Where Winds Meet". Create custom macros to cast combos that can be used in game.',
      tags: ['C#'],
      image: '/media/Bober-macro-maker.png',
    },
    {
      name: 'Min spendings',
      website: 'https://github.com/S0ul3r/min_spendings',
      description: 'Mobile application for android and iOS to track your monthly spendings, so you have better overview how much and on what you are spending your money.',
      tags: ['Dart', 'C++', 'CMake', 'Swift'],
      image: '/media/min_spendings.png',
    },
    {
      name: 'World of Warcraft rotations',
      website: 'https://github.com/S0ul3r/Aurora-Bober-Rogue',
      description: 'Aurora Bober Rogue rotation by S0ul3r for World of Warcraft.',
      tags: ['Lua'],
      image: 'https://img.youtube.com/vi/kZ0IGSSiYlM/maxresdefault.jpg',
      videoUrl: 'https://www.youtube.com/watch?v=kZ0IGSSiYlM',
    },
    {
      name: 'Rogue Survivor',
      website: 'https://github.com/S0ul3r/Rogue-Survivor',
      description: '2D Unity based rogue-like game.',
      tags: ['C#', 'Unity'],
      image: '/media/Rogue_Survivor.png',
    },
  ],
  skills: [
    { name: 'Programming Languages', keywords: ['TypeScript', 'JavaScript', 'C#', 'SQL', 'Lua', 'Python'] },
    { name: 'Frameworks', keywords: ['.NET Core', 'React', 'Laravel'] },
    { name: 'Cloud & DevOps', keywords: ['Azure', 'Azure DevOps', 'CI/CD'] },
    { name: 'Databases', keywords: ['MySQL', 'PostgreSQL', 'NoSQL'] },
    { name: 'Tools & Practices', keywords: ['GitHub', 'Git', 'Agile', 'Scrum (Scrum Master)'] },
  ],
  languages: [
    { language: 'Polish', fluency: 'Native', flagCode: 'pl' },
    { language: 'English', fluency: 'C2 (Proficient)', flagCode: 'gb' },
  ],
  certifications: [
    { title: 'Microsoft Certified: Azure Fundamentals', issuer: 'Microsoft', date: '2023' },
    { title: 'CCNA: Networking, Security, and Automation', issuer: 'Cisco', date: '2022' },
    { title: 'CCNA: Switching, Routing, and Wireless Essentials', issuer: 'Cisco', date: '2022' },
    { title: 'Python Data Science Toolbox & Unit Testing', issuer: 'Datacamp', date: '2021' },
    { title: 'Skiing Instructor', issuer: 'SITN', date: '2020' },
  ],
  interests: [
    { name: 'Music', keywords: ['Playing piano', 'Indie', 'Electronic', 'Rock'] },
    { name: 'Sports', keywords: ['Skiing', 'Badminton', 'Hockey'] },
    { name: 'Dancing', keywords: ['Ballroom', 'Salsa', 'Son', 'Argentine Tango'] },
  ],
  interestsVideo: {
    url: 'https://www.youtube.com/watch?v=1xnJAcBFodk',
    thumbnail: 'https://img.youtube.com/vi/1xnJAcBFodk/maxresdefault.jpg',
    label: 'Piano playing',
  },
};

export const devicons = {
  'TypeScript': 'devicon-typescript-plain',
  'JavaScript': 'devicon-javascript-plain',
  'C#': 'devicon-csharp-plain',
  'SQL': 'devicon-azuresqldatabase-plain',
  'Lua': 'devicon-lua-plain',
  'Python': 'devicon-python-plain',
  '.NET Core': 'devicon-dotnetcore-plain',
  'React': 'devicon-react-original',
  'React Native': 'devicon-react-original',
  'Laravel': 'devicon-laravel-original',
  'Azure': 'devicon-azure-plain',
  'Azure DevOps': 'devicon-azure-plain',
  'CI/CD': 'devicon-githubactions-plain',
  'MySQL': 'devicon-mysql-plain',
  'PostgreSQL': 'devicon-postgresql-plain',
  'NoSQL': 'devicon-mongodb-plain',
  'GitHub': 'devicon-github-original',
  'Git': 'devicon-git-plain',
  'Unity': 'devicon-unity-plain',
  'PHP': 'devicon-php-plain',
  'HTML': 'devicon-html5-plain',
  'CSS': 'devicon-css3-plain',
  'Dart': 'devicon-dart-plain',
  'C++': 'devicon-cplusplus-plain',
  'CMake': 'devicon-cmake-plain',
  'Swift': 'devicon-swift-plain',
};
